# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Nik Voss'
tagline:          ''
description:      'Pixel Chemist / Game Developer / Computer Science Student.'

url:              http://nikvoss.com
baseurl:          /

author:
  name:           'Niklas Voss'
  url:            http://nikvoss.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
